import assert from 'node:assert/strict';
import test from 'node:test';
import {
  getStructuredTextPreview,
  hasStructuredText,
  parseStructuredTextSegments,
} from './structuredText';

const fullCaveat = '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>';

test('parses local command caveat segments', () => {
  assert.deepEqual(parseStructuredTextSegments(`前文\n${fullCaveat}\n后文`), [
    { type: 'text', text: '前文\n' },
    {
      type: 'local-command-caveat',
      body: 'Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.',
      raw: fullCaveat,
    },
    { type: 'text', text: '\n后文' },
  ]);
});

test('detects structured local command caveats', () => {
  assert.equal(hasStructuredText(fullCaveat), true);
  assert.equal(hasStructuredText('普通用户输入'), false);
});

test('builds preview for full and truncated local command caveats', () => {
  assert.deepEqual(getStructuredTextPreview(fullCaveat), {
    kind: 'local-command-caveat',
    label: '本地命令输出提示',
    detail: '由本地命令生成的消息',
    tooltip: '本地命令输出提示 · 由本地命令生成的消息',
  });

  assert.deepEqual(
    getStructuredTextPreview(
      '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond',
    ),
    {
      kind: 'local-command-caveat',
      label: '本地命令输出提示',
      detail: '由本地命令生成的消息',
      tooltip: '本地命令输出提示 · 由本地命令生成的消息',
    },
  );
});

test('builds command preview through structured preview API', () => {
  assert.deepEqual(
    getStructuredTextPreview(
      '<command-message>ponytail:ponytail-audit</command-message><command-name>/ponytail:ponytail-audit</command-name><command-args>审查当前项目所有代码</command-args>',
    ),
    {
      kind: 'command',
      label: '/ponytail:ponytail-audit',
      detail: '审查当前项目所有代码',
      tooltip: '/ponytail:ponytail-audit · 审查当前项目所有代码',
      plugin: 'ponytail',
    },
  );
});

test('parses slash command messages without args as structured command segments', () => {
  const raw = '<command-message>trellis-update-spec</command-message>\n<command-name>/trellis-update-spec</command-name>';

  assert.deepEqual(parseStructuredTextSegments(raw), [
    {
      type: 'command',
      message: 'trellis-update-spec',
      name: '/trellis-update-spec',
      args: '',
      raw,
    },
  ]);
});

test('parses out-of-order command tags as structured command segments', () => {
  const raw = '<command-name>/model</command-name>\n\n<command-message>model</command-message>\n<command-args></command-args>';

  assert.deepEqual(parseStructuredTextSegments(raw), [
    {
      type: 'command',
      message: 'model',
      name: '/model',
      args: '',
      raw,
    },
  ]);
});

test('parses Codex plugin references as structured segments', () => {
  assert.deepEqual(
    parseStructuredTextSegments('前文 [@superpowers](plugin://superpowers@openai-api-curated) 后文'),
    [
      { type: 'text', text: '前文 ' },
      {
        type: 'plugin-reference',
        label: '@superpowers',
        plugin: 'superpowers',
        source: 'openai-api-curated',
        url: 'plugin://superpowers@openai-api-curated',
        raw: '[@superpowers](plugin://superpowers@openai-api-curated)',
      },
      { type: 'text', text: ' 后文' },
    ],
  );
});

test('parses truncated Codex plugin references at the end as structured segments', () => {
  assert.deepEqual(
    parseStructuredTextSegments('[@superpowers](plugin://superpowers@openai-api-curated'),
    [
      {
        type: 'plugin-reference',
        label: '@superpowers',
        plugin: 'superpowers',
        source: 'openai-api-curated',
        url: 'plugin://superpowers@openai-api-curated',
        raw: '[@superpowers](plugin://superpowers@openai-api-curated',
      },
    ],
  );
});

test('builds preview for complete and truncated Codex plugin references', () => {
  assert.deepEqual(getStructuredTextPreview('[@superpowers](plugin://superpowers@openai-api-curated)'), {
    kind: 'plugin-reference',
    label: '@superpowers',
    detail: 'openai-api-curated',
    tooltip: '@superpowers · openai-api-curated',
    plugin: 'superpowers',
    source: 'openai-api-curated',
  });

  assert.deepEqual(getStructuredTextPreview('[@superpowers](plugin://superpowers@openai-api-curated'), {
    kind: 'plugin-reference',
    label: '@superpowers',
    detail: 'openai-api-curated',
    tooltip: '@superpowers · openai-api-curated',
    plugin: 'superpowers',
    source: 'openai-api-curated',
  });
});
