import assert from 'node:assert/strict';
import test from 'node:test';
import { getSessionCardTitleDisplay } from './sessionTitle';

test('renders command-message ai titles as command previews', () => {
  assert.deepEqual(
    getSessionCardTitleDisplay(
      '<command-message>ponytail:ponytail-audit</command-message> <command-name>/ponytail:ponytail-audit</command-name> <command-args>审查当前项目所有代码</command-args>',
      'gpt-5',
    ),
    {
      kind: 'structured',
      label: '/ponytail:ponytail-audit',
      detail: '审查当前项目所有代码',
      icon: '/',
      tone: 'command',
      tooltip: '/ponytail:ponytail-audit · 审查当前项目所有代码',
    },
  );
});

test('keeps ordinary ai titles as plain card titles', () => {
  assert.deepEqual(getSessionCardTitleDisplay('性能优化讨论', 'gpt-5'), {
    kind: 'text',
    text: '性能优化讨论',
  });
});

test('renders command-message model fallbacks as command previews', () => {
  assert.deepEqual(
    getSessionCardTitleDisplay(
      null,
      '<command-message>ponytail:ponytail-review</command-message><command-name>/ponytail:ponytail-review</command-name><command-args>审查当前项目所有代码</command-args>',
    ),
    {
      kind: 'structured',
      label: '/ponytail:ponytail-review',
      detail: '审查当前项目所有代码',
      icon: '/',
      tone: 'command',
      tooltip: '/ponytail:ponytail-review · 审查当前项目所有代码',
    },
  );
});

test('renders local command caveat titles as structured previews', () => {
  assert.deepEqual(
    getSessionCardTitleDisplay(
      '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond',
      'deepseek-v4-pro',
    ),
    {
      kind: 'structured',
      label: '本地命令输出提示',
      detail: '由本地命令生成的消息',
      icon: '!',
      tone: 'warning',
      tooltip: '本地命令输出提示 · 由本地命令生成的消息',
    },
  );
});

test('renders Codex plugin reference titles as structured previews', () => {
  assert.deepEqual(
    getSessionCardTitleDisplay(
      '[@superpowers](plugin://superpowers@openai-api-curated',
      'gpt-5',
    ),
    {
      kind: 'structured',
      label: '@superpowers',
      detail: 'openai-api-curated',
      icon: '@',
      tone: 'plugin',
      tooltip: '@superpowers · openai-api-curated',
    },
  );
});

test('falls back to model or unknown when ai title is empty', () => {
  assert.deepEqual(getSessionCardTitleDisplay('', 'gpt-5'), {
    kind: 'text',
    text: 'gpt-5',
  });
  assert.deepEqual(getSessionCardTitleDisplay(null, ''), {
    kind: 'text',
    text: 'unknown',
  });
});
